mod audio;
mod cleanup;
mod commands;
mod errors;
mod events;
mod migrations;
mod platform;
mod recording;
mod state;
mod ui;

// Auto-generated extern crate declarations for all jona-engine-* crates.
// Forces the linker to include them so their `inventory::submit!` registrations
// are present at runtime. Generated by build.rs from Cargo.toml dependencies.
include!(concat!(env!("OUT_DIR"), "/engine_links.rs"));

rust_i18n::i18n!("../src/i18n");

use state::AppState;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use tauri::{Emitter, Manager};

/// Resolve the effective locale ("fr" or "en") from preferences.
pub fn resolve_locale(app_locale: &str) -> String {
    if app_locale != "auto" {
        return app_locale.to_string();
    }
    let sys = sys_locale::get_locale().unwrap_or_else(|| "en".to_string());
    if sys.starts_with("fr") { "fr".to_string() } else { "en".to_string() }
}

/// Fetch the latest spellcheck manifest from GitHub and cache it on disk.
/// If the manifest changed, emit MODELS_CHANGED so the frontend refreshes.
fn refresh_spellcheck_manifest(app: &tauri::AppHandle) {
    const URL: &str = "https://github.com/JonaWhisper/jonawhisper-spellcheck-dicts/releases/latest/download/manifest.json";

    let dest = jona_types::models_dir()
        .join("spellcheck")
        .join("manifest.json");

    let client = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build();
    let client = match client {
        Ok(c) => c,
        Err(e) => {
            log::warn!("Spellcheck manifest refresh: failed to create client: {}", e);
            return;
        }
    };

    match client.get(URL).send().and_then(|r| r.error_for_status()) {
        Ok(resp) => {
            let body = match resp.text() {
                Ok(b) => b,
                Err(e) => {
                    log::warn!("Spellcheck manifest refresh: read error: {}", e);
                    return;
                }
            };

            // Only write + emit if content changed
            let old = std::fs::read_to_string(&dest).unwrap_or_default();
            if body != old {
                std::fs::create_dir_all(dest.parent().unwrap()).ok();
                if let Err(e) = std::fs::write(&dest, &body) {
                    log::warn!("Spellcheck manifest refresh: write error: {}", e);
                    return;
                }
                log::info!("Spellcheck manifest updated ({} bytes)", body.len());
                let _ = app.emit(events::MODELS_CHANGED, ());
            } else {
                log::debug!("Spellcheck manifest unchanged");
            }
        }
        Err(e) => {
            log::debug!("Spellcheck manifest refresh failed (offline?): {}", e);
        }
    }
}

/// Scan all downloaded models and emit an event if any have updates available.
fn check_model_updates(app: &tauri::AppHandle) {
    let catalog = jona_engines::EngineCatalog::global();
    let updatable: Vec<String> = catalog
        .downloaded_models()
        .iter()
        .filter(|m| {
            jona_engines::downloader::check_model_update(m)
                == jona_engines::downloader::UpdateStatus::UpdateAvailable
        })
        .map(|m| m.id.clone())
        .collect();

    if !updatable.is_empty() {
        log::info!("Model updates available: {:?}", updatable);
        let _ = app.emit(events::MODEL_UPDATES_AVAILABLE, &updatable);
    } else {
        log::debug!("All downloaded models are up to date");
    }
}

/// Wrapper to store the hotkey update channel sender in Tauri managed state.
pub struct HotkeyUpdateSender(pub crossbeam_channel::Sender<platform::hotkey::HotkeyUpdate>);

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    env_logger::init();

    // Initialize the engine catalog from inventory auto-registration.
    // Each engine crate registers itself via `inventory::submit!`.
    jona_engines::EngineCatalog::init_auto();

    recording::cleanup_orphan_audio_files();

    let app_state = Arc::new(AppState::default());

    // Set Rust i18n locale from saved preferences
    {
        let locale = app_state.settings.lock().unwrap().app_locale.clone();
        rust_i18n::set_locale(&resolve_locale(&locale));
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_clipboard_manager::init())


        .manage(app_state.clone())
        .invoke_handler(tauri::generate_handler![
            commands::audio::get_audio_devices,
            commands::audio::start_mic_test,
            commands::audio::stop_mic_test,
            commands::engines::get_engines,
            commands::engines::get_models,
            commands::engines::download_model_cmd,
            commands::engines::delete_model_cmd,
            commands::engines::pause_download,
            commands::engines::cancel_download,
            commands::engines::get_languages,
            commands::history::get_history,
            commands::history::delete_history_entry,
            commands::history::delete_history_day,
            commands::history::clear_history,
            commands::providers::add_provider,
            commands::providers::remove_provider,
            commands::providers::update_provider,
            commands::providers::get_providers,
            commands::providers::fetch_provider_models,
            commands::settings::get_settings,
            commands::settings::set_setting,
            commands::settings::get_system_locale,
            commands::settings::get_launch_at_login_status,
            commands::settings::set_launch_at_login,
            commands::permissions::get_permissions,
            commands::permissions::request_permission,
            commands::permissions::start_monitoring,
            commands::permissions::enable_monitoring,
            commands::app::get_app_state,
            commands::app::start_shortcut_capture,
            commands::app::stop_shortcut_capture,
            commands::app::simulate_pill_test,
        ])
        .setup(move |app| {
            #[cfg(target_os = "macos")]
            {
                app.set_activation_policy(tauri::ActivationPolicy::Accessory);
            }

            // Panel window is pre-created hidden (tauri.conf.json) — intercept close → hide
            if let Some(win) = app.get_webview_window("panel") {
                let win2 = win.clone();
                win.on_window_event(move |event| {
                    if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                        api.prevent_close();
                        let _ = win2.hide();
                    }
                });
            } else {
                log::warn!("Panel window not found at startup — check tauri.conf.json");
            }

            ui::tray::setup_tray(app.handle())?;

            // Audio thread (cpal::Stream is not Send)
            let (cmd_tx, spectrum_data, reply_rx, stream_error) =
                recording::spawn_audio_thread();

            // Mic test sender (clone before cmd_tx is moved)
            app.manage(recording::MicTestSender(cmd_tx.clone()));

            // Recording state (Send-safe: only channels, no cpal::Stream)
            let rec_state = Arc::new(std::sync::Mutex::new(recording::new_recording_state(
                cmd_tx.clone(),
                reply_rx,
            )));

            // Deferred monitoring flag — hotkey thread waits for this
            let monitor_enabled = Arc::new(AtomicBool::new(false));
            app.manage(monitor_enabled.clone());

            // Start CGEvent tap hotkey monitor (with cancel key support)
            let (hotkey_str, cancel_str) = {
                let s = app_state.settings.lock().unwrap();
                (s.hotkey_option.clone(), s.cancel_shortcut.clone())
            };
            let initial_record = platform::hotkey::Shortcut::parse(&hotkey_str);
            let initial_cancel = platform::hotkey::Shortcut::parse(&cancel_str);
            let capture_control = Arc::new(platform::hotkey::CaptureControl::new());
            let (hotkey_rx, hotkey_update_tx) =
                platform::hotkey::start_monitor(initial_record, initial_cancel, monitor_enabled.clone(), capture_control.clone());
            app.manage(capture_control);
            app.manage(HotkeyUpdateSender(hotkey_update_tx));

            // Hotkey event processing thread
            recording::spawn_hotkey_handler(
                hotkey_rx,
                app.handle().clone(),
                app_state.clone(),
                rec_state,
            );

            // Check permissions and show setup if needed
            let report = platform::check_permissions();
            if report.all_granted() {
                monitor_enabled.store(true, Ordering::SeqCst);
            } else {
                ui::tray::open_fixed_window(app.handle(), "setup", &rust_i18n::t!("window.setup"), "/setup", 420.0, 450.0);
            }

            // Refresh spellcheck manifest in background, then check for model updates
            {
                let handle = app.handle().clone();
                std::thread::spawn(move || {
                    refresh_spellcheck_manifest(&handle);
                    check_model_updates(&handle);
                });
            }

            // Spectrum emission (30fps) + stream error detection
            recording::spawn_spectrum_emitter(
                app.handle().clone(),
                app_state,
                cmd_tx,
                spectrum_data,
                stream_error,
            );

            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|_app, event| {
            // Keep the app running when the last window closes (menu bar app).
            // code=None → window close, code=Some → explicit app.exit() (e.g. quit menu item)
            if let tauri::RunEvent::ExitRequested { api, code, .. } = event {
                if code.is_none() {
                    api.prevent_exit();
                }
            }
        });
}

#[cfg(test)]
mod tests {
    use jona_engines::EngineCatalog;
    use std::sync::Once;

    static INIT: Once = Once::new();

    /// Ensure the engine catalog is initialized exactly once across all tests.
    fn ensure_catalog() {
        INIT.call_once(|| {
            EngineCatalog::init_auto();
        });
    }

    #[test]
    fn all_engines_registered() {
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let engines = catalog.engine_infos();
        assert!(
            engines.len() >= 10,
            "Expected at least 10 engines, got {}: {:?}",
            engines.len(),
            engines.iter().map(|e| &e.id).collect::<Vec<_>>()
        );
    }

    #[test]
    fn all_models_have_valid_metadata() {
        ensure_catalog();
        let catalog = EngineCatalog::global();
        for model in catalog.all_models() {
            assert!(!model.id.is_empty(), "Model has empty id");
            assert!(!model.label.is_empty(), "Model {} has empty label", model.id);
            assert!(!model.engine_id.is_empty(), "Model {} has empty engine_id", model.id);

            // Collect all URLs (single-file URL + multi-file URLs)
            let mut urls = Vec::new();
            if !model.url.is_empty() {
                urls.push(model.url.as_str());
            }
            if let jona_types::DownloadType::MultiFile { ref files } = model.download_type {
                for f in files {
                    urls.push(f.url.as_str());
                }
            }
            // All download URLs should be HTTPS
            for url in urls {
                assert!(
                    url.starts_with("https://"),
                    "Model {} has non-HTTPS URL: {}",
                    model.id,
                    url
                );
            }
        }
    }

    #[test]
    fn user_selected_model_can_be_found_in_catalog() {
        // When the user selects a model ID in preferences, the backend must
        // be able to look it up to load the correct engine for transcription.
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let model = catalog.model_by_id("whisper:tiny");
        assert!(model.is_some(), "whisper:tiny should be findable by ID");
    }

    #[test]
    fn engine_can_be_found_by_id() {
        // Engine lookup is used to route transcription to the correct backend.
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let engine = catalog.engine_by_id("whisper");
        assert!(engine.is_some(), "whisper engine should be findable by ID");
    }

    #[test]
    fn no_duplicate_model_ids() {
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let models = catalog.all_models();
        let mut seen = std::collections::HashSet::new();
        for model in &models {
            assert!(
                seen.insert(&model.id),
                "Duplicate model ID found: {}",
                model.id
            );
        }
    }

    #[test]
    fn no_duplicate_engine_ids() {
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let engines = catalog.engine_infos();
        let mut seen = std::collections::HashSet::new();
        for engine in &engines {
            assert!(
                seen.insert(&engine.id),
                "Duplicate engine ID found: {}",
                engine.id
            );
        }
    }

    #[test]
    fn resolve_locale_auto_french() {
        // When system locale starts with "fr", should resolve to "fr"
        // We can't control sys_locale in tests, but we can test non-auto paths
        assert_eq!(super::resolve_locale("fr"), "fr");
        assert_eq!(super::resolve_locale("en"), "en");
    }

    #[test]
    fn resolve_locale_explicit() {
        assert_eq!(super::resolve_locale("fr"), "fr");
        assert_eq!(super::resolve_locale("en"), "en");
        // auto depends on system locale, just ensure it returns something valid
        let result = super::resolve_locale("auto");
        assert!(result == "fr" || result == "en", "auto should resolve to fr or en, got: {}", result);
    }
}
