mod audio;
mod cleanup;
mod commands;
mod errors;
mod events;
mod migrations;
mod platform;
mod recording;
mod state;
mod ui;

// Auto-generated extern crate declarations for all jona-engine-* and jona-provider-* crates.
// Forces the linker to include them so their `inventory::submit!` registrations
// are present at runtime. Generated by build.rs from Cargo.toml dependencies.
include!(concat!(env!("OUT_DIR"), "/inventory_links.rs"));

rust_i18n::i18n!("../src/i18n");

use state::AppState;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use tauri::{Emitter, Manager};

/// Initialize logging: write to both stderr and a log file on disk.
/// Log file: ~/Library/Application Support/JonaWhisper/logs/jona-whisper-{timestamp}.log
fn init_logging(log_retention: &str) {
    use simplelog::*;
    use std::fs;

    let log_dir = jona_types::config_dir().join("logs");
    let _ = fs::create_dir_all(&log_dir);

    // Timestamped filename: jona-whisper-1741480800.log (Unix timestamp)
    let ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let log_path = log_dir.join(format!("jona-whisper-{}.log", ts));

    prune_old_logs(&log_dir, log_retention);

    let config = ConfigBuilder::new()
        .set_time_format_rfc3339()
        .set_target_level(LevelFilter::Off)
        .build();

    let mut loggers: Vec<Box<dyn SharedLogger>> = vec![
        TermLogger::new(LevelFilter::Info, config.clone(), TerminalMode::Stderr, ColorChoice::Auto),
    ];

    if let Ok(file) = fs::File::create(&log_path) {
        loggers.push(WriteLogger::new(LevelFilter::Debug, config, file));
    }

    let _ = CombinedLogger::init(loggers);
    log::info!("Logging to {} (retention: {})", log_path.display(), log_retention);
}

/// Remove old log files based on retention mode.
/// - "previous": keep only the most recent 1 (current will be created after)
/// - "3days"/"7days"/"30days": keep files from last N days
/// - "all": never delete
fn prune_old_logs(log_dir: &std::path::Path, retention: &str) {
    if retention == "all" {
        return;
    }

    let mut logs: Vec<std::path::PathBuf> = std::fs::read_dir(log_dir)
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| n.starts_with("jona-whisper-") && n.ends_with(".log"))
        })
        .map(|e| e.path())
        .collect();
    logs.sort();

    match retention {
        "previous" => {
            // Keep only the most recent file (the new one will be created after pruning)
            if logs.len() > 1 {
                for old in &logs[..logs.len() - 1] {
                    let _ = std::fs::remove_file(old);
                }
            }
        }
        days_str => {
            // Parse "3days", "7days", "30days" → keep files younger than N days
            let days: u64 = days_str.trim_end_matches("days").parse().unwrap_or(7);
            let cutoff = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs()
                .saturating_sub(days * 86400);

            for path in &logs {
                // Extract timestamp from filename: jona-whisper-{ts}.log
                let dominated = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .and_then(|s| s.strip_prefix("jona-whisper-"))
                    .and_then(|s| s.parse::<u64>().ok())
                    .unwrap_or(u64::MAX);
                if dominated < cutoff {
                    let _ = std::fs::remove_file(path);
                }
            }
        }
    }
}

/// Resolve the effective locale ("fr" or "en") from preferences.
pub fn resolve_locale(app_locale: &str) -> String {
    if app_locale != "auto" {
        return app_locale.to_string();
    }
    let sys = sys_locale::get_locale().unwrap_or_else(|| "en".to_string());
    if sys.starts_with("fr") { "fr".to_string() } else { "en".to_string() }
}

/// Fetch the latest spellcheck manifest from GitHub and cache it on disk.
/// If the manifest changed, emit MODELS_CHANGED so the frontend refreshes.
fn refresh_spellcheck_manifest(app: &tauri::AppHandle) {
    const URL: &str = "https://github.com/JonaWhisper/jonawhisper-spellcheck-dicts/releases/latest/download/manifest.json";

    let dest = jona_types::models_dir()
        .join("spellcheck")
        .join("manifest.json");

    let client = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build();
    let client = match client {
        Ok(c) => c,
        Err(e) => {
            log::warn!("Spellcheck manifest refresh: failed to create client: {}", e);
            return;
        }
    };

    match client.get(URL).send().and_then(|r| r.error_for_status()) {
        Ok(resp) => {
            let body = match resp.text() {
                Ok(b) => b,
                Err(e) => {
                    log::warn!("Spellcheck manifest refresh: read error: {}", e);
                    return;
                }
            };

            // Only write + emit if content changed
            let old = std::fs::read_to_string(&dest).unwrap_or_default();
            if body != old {
                std::fs::create_dir_all(dest.parent().unwrap()).ok();
                if let Err(e) = std::fs::write(&dest, &body) {
                    log::warn!("Spellcheck manifest refresh: write error: {}", e);
                    return;
                }
                log::info!("Spellcheck manifest updated ({} bytes)", body.len());
                let _ = app.emit(events::MODELS_CHANGED, ());
            } else {
                log::debug!("Spellcheck manifest unchanged");
            }
        }
        Err(e) => {
            log::debug!("Spellcheck manifest refresh failed (offline?): {}", e);
        }
    }
}

/// Scan all downloaded models and emit an event if any have updates available.
fn check_model_updates(app: &tauri::AppHandle) {
    let catalog = jona_engines::EngineCatalog::global();
    let updatable: Vec<String> = catalog
        .downloaded_models()
        .iter()
        .filter(|m| {
            jona_engines::downloader::check_model_update(m)
                == jona_engines::downloader::UpdateStatus::UpdateAvailable
        })
        .map(|m| m.id.clone())
        .collect();

    if !updatable.is_empty() {
        log::info!("Model updates available: {:?}", updatable);
        let _ = app.emit(events::MODEL_UPDATES_AVAILABLE, &updatable);
    } else {
        log::debug!("All downloaded models are up to date");
    }
}

/// Wrapper to store the hotkey update channel sender in Tauri managed state.
pub struct HotkeyUpdateSender(pub crossbeam_channel::Sender<platform::hotkey::HotkeyUpdate>);

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Initialize catalogs before AppState — migrations call jona_provider::preset().
    jona_engines::EngineCatalog::init_auto();
    jona_provider::ProviderCatalog::init_auto();

    let app_state = Arc::new(AppState::default());

    // Read log retention before initializing logging (needs prefs)
    let log_retention = app_state.settings.lock().unwrap().log_retention.clone();
    init_logging(&log_retention);

    recording::cleanup_orphan_audio_files();

    // Apply saved log level and locale from preferences
    {
        let s = app_state.settings.lock().unwrap();
        let level = commands::settings::parse_log_level(&s.log_level);
        log::set_max_level(level);
        log::info!("Log level: {}", level);
        rust_i18n::set_locale(&resolve_locale(&s.app_locale));
    }

    // Run auto-detection after logging is initialized
    app_state.run_detection();

    tauri::Builder::default()
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())


        .manage(app_state.clone())
        .invoke_handler(tauri::generate_handler![
            commands::audio::get_audio_devices,
            commands::audio::start_mic_test,
            commands::audio::stop_mic_test,
            commands::engines::get_engines,
            commands::engines::get_models,
            commands::engines::download_model_cmd,
            commands::engines::delete_model_cmd,
            commands::engines::pause_download,
            commands::engines::cancel_download,
            commands::engines::get_languages,
            commands::history::get_history,
            commands::history::delete_history_entry,
            commands::history::delete_history_day,
            commands::history::clear_history,
            commands::providers::add_provider,
            commands::providers::remove_provider,
            commands::providers::update_provider,
            commands::providers::get_providers,
            commands::providers::fetch_provider_models,
            commands::providers::get_provider_presets,
            commands::providers::open_provider_form_window,
            commands::providers::detect_providers,
            commands::providers::toggle_provider_enabled,
            commands::settings::get_settings,
            commands::settings::set_setting,
            commands::settings::get_system_locale,
            commands::settings::get_user_dict,
            commands::settings::save_user_dict,
            commands::settings::get_launch_at_login_status,
            commands::settings::set_launch_at_login,
            commands::settings::open_logs_folder,
            commands::permissions::get_permissions,
            commands::permissions::request_permission,
            commands::permissions::start_monitoring,
            commands::permissions::enable_monitoring,
            commands::app::get_app_state,
            commands::app::start_shortcut_capture,
            commands::app::stop_shortcut_capture,
            #[cfg(debug_assertions)]
            commands::app::simulate_pill_test,
            commands::app::check_for_update,
            commands::app::install_update,
        ])
        .setup(move |app| {
            #[cfg(target_os = "macos")]
            {
                app.set_activation_policy(tauri::ActivationPolicy::Accessory);
            }

            // Panel window is pre-created hidden (tauri.conf.json) — intercept close → hide
            if let Some(win) = app.get_webview_window("panel") {
                let win2 = win.clone();
                win.on_window_event(move |event| {
                    if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                        api.prevent_close();
                        let _ = win2.hide();
                    }
                });
            } else {
                log::warn!("Panel window not found at startup — check tauri.conf.json");
            }

            ui::tray::setup_tray(app.handle())?;

            // Audio thread (cpal::Stream is not Send)
            let recording::AudioThreadHandles {
                cmd_tx, spectrum_data, reply_rx, stream_error, samples_received,
            } = recording::spawn_audio_thread();

            // Mic test sender (clone before cmd_tx is moved)
            app.manage(recording::MicTestSender(cmd_tx.clone()));

            // Clone before moving into RecordingState — spectrum emitter needs it too
            let samples_received_for_spectrum = samples_received.clone();

            // Recording state (Send-safe: only channels, no cpal::Stream)
            let rec_state = Arc::new(std::sync::Mutex::new(recording::new_recording_state(
                cmd_tx.clone(),
                reply_rx,
                samples_received,
            )));

            // Deferred monitoring flag — hotkey thread waits for this
            let monitor_enabled = Arc::new(AtomicBool::new(false));
            app.manage(monitor_enabled.clone());

            // Start CGEvent tap hotkey monitor (with cancel key support)
            let (hotkey_str, cancel_str) = {
                let s = app_state.settings.lock().unwrap();
                (s.hotkey_option.clone(), s.cancel_shortcut.clone())
            };
            let initial_record = platform::hotkey::Shortcut::parse(&hotkey_str);
            let initial_cancel = platform::hotkey::Shortcut::parse(&cancel_str);
            let capture_control = Arc::new(platform::hotkey::CaptureControl::new());
            let (hotkey_rx, hotkey_update_tx) =
                platform::hotkey::start_monitor(initial_record, initial_cancel, monitor_enabled.clone(), capture_control.clone());
            app.manage(capture_control);
            app.manage(HotkeyUpdateSender(hotkey_update_tx));

            // Hotkey event processing thread
            recording::spawn_hotkey_handler(
                hotkey_rx,
                app.handle().clone(),
                app_state.clone(),
                rec_state,
            );

            // Check permissions and show setup if needed
            let report = platform::check_permissions();
            if report.all_granted() {
                monitor_enabled.store(true, Ordering::Relaxed);
            } else {
                ui::tray::open_fixed_window(app.handle(), "setup", &rust_i18n::t!("window.setup"), "/setup", 420.0, 450.0);
            }

            // Refresh spellcheck manifest in background, then check for model updates
            {
                let handle = app.handle().clone();
                std::thread::spawn(move || {
                    refresh_spellcheck_manifest(&handle);
                    check_model_updates(&handle);
                });
            }

            // Spectrum emission (30fps) + stream error detection
            recording::spawn_spectrum_emitter(
                app.handle().clone(),
                app_state,
                cmd_tx,
                spectrum_data,
                stream_error,
                samples_received_for_spectrum,
            );

            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|_app, event| {
            // Keep the app running when the last window closes (menu bar app).
            // code=None → window close, code=Some → explicit app.exit() (e.g. quit menu item)
            if let tauri::RunEvent::ExitRequested { api, code, .. } = event {
                if code.is_none() {
                    api.prevent_exit();
                }
            }
        });
}

#[cfg(test)]
mod tests {
    use jona_engines::EngineCatalog;
    use jona_provider::ProviderCatalog;
    use std::sync::Once;

    static INIT: Once = Once::new();

    /// Ensure both catalogs are initialized exactly once across all tests.
    fn ensure_catalog() {
        INIT.call_once(|| {
            EngineCatalog::init_auto();
            ProviderCatalog::init_auto();
        });
    }

    #[test]
    fn all_engines_registered() {
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let engines = catalog.engine_infos();
        assert!(
            engines.len() >= 10,
            "Expected at least 10 engines, got {}: {:?}",
            engines.len(),
            engines.iter().map(|e| &e.id).collect::<Vec<_>>()
        );
    }

    #[test]
    fn all_models_have_valid_metadata() {
        ensure_catalog();
        let catalog = EngineCatalog::global();
        for model in catalog.all_models() {
            assert!(!model.id.is_empty(), "Model has empty id");
            assert!(!model.label.is_empty(), "Model {} has empty label", model.id);
            assert!(!model.engine_id.is_empty(), "Model {} has empty engine_id", model.id);

            // Collect all URLs (single-file URL + multi-file URLs)
            let mut urls = Vec::new();
            if !model.url.is_empty() {
                urls.push(model.url.as_str());
            }
            if let jona_types::DownloadType::MultiFile { ref files } = model.download_type {
                for f in files {
                    urls.push(f.url.as_str());
                }
            }
            // All download URLs should be HTTPS
            for url in urls {
                assert!(
                    url.starts_with("https://"),
                    "Model {} has non-HTTPS URL: {}",
                    model.id,
                    url
                );
            }
        }
    }

    #[test]
    fn user_selected_model_can_be_found_in_catalog() {
        // When the user selects a model ID in preferences, the backend must
        // be able to look it up to load the correct engine for transcription.
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let model = catalog.model_by_id("whisper:tiny");
        assert!(model.is_some(), "whisper:tiny should be findable by ID");
    }

    #[test]
    fn engine_can_be_found_by_id() {
        // Engine lookup is used to route transcription to the correct backend.
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let engine = catalog.engine_by_id("whisper");
        assert!(engine.is_some(), "whisper engine should be findable by ID");
    }

    #[test]
    fn no_duplicate_model_ids() {
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let models = catalog.all_models();
        let mut seen = std::collections::HashSet::new();
        for model in &models {
            assert!(
                seen.insert(&model.id),
                "Duplicate model ID found: {}",
                model.id
            );
        }
    }

    #[test]
    fn no_duplicate_engine_ids() {
        ensure_catalog();
        let catalog = EngineCatalog::global();
        let engines = catalog.engine_infos();
        let mut seen = std::collections::HashSet::new();
        for engine in &engines {
            assert!(
                seen.insert(&engine.id),
                "Duplicate engine ID found: {}",
                engine.id
            );
        }
    }

    // -- Provider catalog tests --

    #[test]
    fn provider_catalog_has_backends() {
        ensure_catalog();
        let presets = jona_provider::presets();
        assert!(!presets.is_empty(), "Should have at least one preset");
        // Verify openai preset exists AND its backend resolves
        let openai = jona_provider::preset("openai");
        assert!(openai.is_some(), "openai preset should exist");
        // backend() panics if not found — this validates the backend is registered
        let _ = jona_provider::backend("openai");
    }

    #[test]
    fn provider_presets_sorted_by_id() {
        ensure_catalog();
        let presets = jona_provider::presets();
        for w in presets.windows(2) {
            assert!(
                w[0].id <= w[1].id,
                "Presets not sorted: {} > {}",
                w[0].id,
                w[1].id
            );
        }
    }

    #[test]
    fn no_duplicate_preset_ids() {
        ensure_catalog();
        let presets = jona_provider::presets();
        let mut seen = std::collections::HashSet::new();
        for p in presets {
            assert!(
                seen.insert(p.id),
                "Duplicate preset ID: {}",
                p.id
            );
        }
    }

    #[test]
    fn preset_base_urls_are_https() {
        ensure_catalog();
        for p in jona_provider::presets() {
            if p.id == "openai-compatible" {
                continue; // User-provided URL, no preset base_url
            }
            assert!(
                p.base_url.starts_with("https://"),
                "Preset {} has non-HTTPS URL: {}",
                p.id,
                p.base_url
            );
        }
    }

    #[test]
    fn preset_backend_ids_resolve() {
        ensure_catalog();
        for p in jona_provider::presets() {
            // backend() panics if not found — this validates referential integrity
            let _ = jona_provider::backend(p.backend_id);
        }
    }

    #[test]
    fn asr_presets_have_default_models() {
        ensure_catalog();
        for p in jona_provider::presets() {
            if p.supports_asr && !matches!(p.id, "azure-openai" | "openai-compatible") {
                // Azure OpenAI models depend on user deployments, openai-compatible is user-provided
                assert!(
                    !p.default_asr_models.is_empty(),
                    "Preset {} supports ASR but has no default ASR models",
                    p.id
                );
            }
        }
    }

    #[test]
    fn llm_presets_have_default_models() {
        ensure_catalog();
        for p in jona_provider::presets() {
            if p.supports_llm && !matches!(p.id, "openrouter" | "azure-openai" | "openai-compatible") {
                // OpenRouter/Azure OpenAI/openai-compatible: models depend on user config
                assert!(
                    !p.default_llm_models.is_empty(),
                    "Preset {} supports LLM but has no default LLM models",
                    p.id
                );
            }
        }
    }

    #[test]
    fn preset_gradients_are_valid_css() {
        ensure_catalog();
        for p in jona_provider::presets() {
            assert!(
                p.gradient.starts_with("linear-gradient("),
                "Preset {} has invalid gradient: {}",
                p.id,
                p.gradient
            );
        }
    }

    #[test]
    fn preset_lookup_nonexistent_returns_none() {
        ensure_catalog();
        assert!(jona_provider::preset("nonexistent_provider_xyz").is_none());
    }

    #[test]
    fn backend_for_known_preset_provider() {
        ensure_catalog();
        let provider = jona_types::Provider {
            id: "p1".into(),
            name: "Test".into(),
            kind: "openai".into(),
            url: "https://api.openai.com/v1".into(),
            api_key: String::new(),
            allow_insecure: false,
            cached_models: vec![],
            supports_asr: true,
            supports_llm: true,
            api_format: None,
            extra: Default::default(),
            enabled: true,
            source: None,
        };
        // Should not panic — resolves preset → backend
        let _ = jona_provider::backend_for_provider(&provider);
    }

    #[test]
    fn backend_for_custom_provider_uses_api_format() {
        ensure_catalog();
        // Use "anthropic" format (non-default) to verify the override path works
        // Legacy "custom" kind has no preset match → falls back to api_format
        let provider = jona_types::Provider {
            id: "p2".into(),
            name: "Custom".into(),
            kind: "custom".into(),
            url: "https://my-server.local/v1".into(),
            api_key: String::new(),
            allow_insecure: false,
            cached_models: vec![],
            supports_asr: false,
            supports_llm: true,
            api_format: Some("anthropic".into()),
            extra: Default::default(),
            enabled: true,
            source: None,
        };
        // Should resolve to the anthropic backend without panicking
        let _ = jona_provider::backend_for_provider(&provider);
    }

    #[test]
    fn sambanova_preset_supports_asr_and_llm() {
        ensure_catalog();
        let p = jona_provider::preset("sambanova").expect("sambanova preset should exist");
        assert!(p.supports_asr);
        assert!(p.supports_llm);
        assert!(p.default_asr_models.contains(&"whisper-large-v3"));
    }

    #[test]
    fn nebius_preset_supports_llm_only() {
        ensure_catalog();
        let p = jona_provider::preset("nebius").expect("nebius preset should exist");
        assert!(!p.supports_asr);
        assert!(p.supports_llm);
        assert!(p.default_asr_models.is_empty());
    }

    #[test]
    fn resolve_locale_auto_french() {
        // When system locale starts with "fr", should resolve to "fr"
        // We can't control sys_locale in tests, but we can test non-auto paths
        assert_eq!(super::resolve_locale("fr"), "fr");
        assert_eq!(super::resolve_locale("en"), "en");
    }

    #[test]
    fn resolve_locale_explicit() {
        assert_eq!(super::resolve_locale("fr"), "fr");
        assert_eq!(super::resolve_locale("en"), "en");
        // auto depends on system locale, just ensure it returns something valid
        let result = super::resolve_locale("auto");
        assert!(result == "fr" || result == "en", "auto should resolve to fr or en, got: {}", result);
    }

    // -- Auto-detection tests --

    fn test_provider(id: &str, source: Option<&str>, enabled: bool) -> jona_types::Provider {
        jona_types::Provider {
            id: id.into(),
            name: "Test".into(),
            kind: "anthropic".into(),
            url: "https://api.anthropic.com/v1".into(),
            api_key: "sk-test".into(),
            allow_insecure: false,
            cached_models: vec![],
            supports_asr: false,
            supports_llm: true,
            api_format: None,
            extra: Default::default(),
            enabled,
            source: source.map(|s| s.to_string()),
        }
    }

    #[test]
    fn find_provider_manual() {
        let state = crate::state::AppState::test_instance();
        state.settings.lock().unwrap().providers.push(test_provider("manual-1", None, true));
        let found = state.find_provider("manual-1");
        assert!(found.is_some());
        assert_eq!(found.unwrap().id, "manual-1");
    }

    #[test]
    fn find_provider_detected() {
        let state = crate::state::AppState::test_instance();
        state.detected_providers.lock().unwrap().push(test_provider("auto-det-1", Some("test-detector"), true));
        let found = state.find_provider("auto-det-1");
        assert!(found.is_some());
        assert_eq!(found.unwrap().id, "auto-det-1");
    }

    #[test]
    fn find_provider_not_found() {
        let state = crate::state::AppState::test_instance();
        assert!(state.find_provider("nonexistent").is_none());
    }

    #[test]
    fn find_provider_manual_takes_precedence() {
        let state = crate::state::AppState::test_instance();
        state.settings.lock().unwrap().providers.push(test_provider("same-id", None, true));
        state.detected_providers.lock().unwrap().push(test_provider("same-id", Some("det"), false));
        let found = state.find_provider("same-id").unwrap();
        // Manual provider wins (no source)
        assert!(found.source.is_none());
    }

    #[test]
    fn get_providers_includes_detected() {
        let state = crate::state::AppState::test_instance();
        state.settings.lock().unwrap().providers.push(test_provider("manual-1", None, true));
        state.detected_providers.lock().unwrap().push(test_provider("auto-1", Some("det"), false));
        let s = state.settings.lock().unwrap();
        let manual: Vec<_> = s.providers.clone();
        drop(s);
        let detected = state.detected_providers.lock().unwrap().clone();
        assert_eq!(manual.len() + detected.len(), 2);
    }

    #[test]
    fn toggle_detected_provider_enabled() {
        let state = crate::state::AppState::test_instance();
        state.detected_providers.lock().unwrap().push(test_provider("auto-1", Some("det"), false));
        // Simulate toggle
        {
            let mut detected = state.detected_providers.lock().unwrap();
            if let Some(p) = detected.iter_mut().find(|p| p.id == "auto-1") {
                p.enabled = true;
            }
        }
        let detected = state.detected_providers.lock().unwrap();
        assert!(detected[0].enabled);
    }

    #[test]
    fn mask_provider_hides_detected_api_key() {
        let p = test_provider("auto-1", Some("det"), true);
        assert!(!p.api_key.is_empty());
        // mask_value is the same function used in mask_provider
        let masked = jona_types::mask_value(&p.api_key);
        assert!(masked.starts_with('\u{2022}')); // bullet char
        assert!(!masked.contains("sk-test"));
    }

    #[test]
    fn refresh_credential_returns_none_for_unknown_detector() {
        ensure_catalog();
        let result = jona_provider::refresh_credential("nonexistent-detector", "anthropic");
        assert!(result.is_none());
    }
}
